
# name = input("enter name: ")
# surname = input("enter surname: ")
# gender = input ("enter gender: ")
# age = input("enter age: ")
# tribe = input ("enter tribe: ")
# occupation = input("enter occupation: ")
# print(f"your information is  \n Name: {name} \n Surname: {surname} \n Gender: {gender} \n Age: {age} \n Tribe: {tribe} \n Occupation: {occupation} ")
name = input("Enter your first name :")
lastname = input("Enter your lastname: ")
age = input("Enter your age: ")
gender = input("Are you male or f emale:")
state = input("Enter yout state of origin: ")
occupation = input("What is your occupation: ")
tribe = input("what is your tribe: ")
print()
print("customers Profile:\t")
print("\tFull Name-" ,name, lastname)
print("\tAge -",age)
print("\tGender -",gender)
print("\tState of origin -",state)
print("\tOccupation -",occupation)
print("\tTribe -",tribe)

name = input("enter name: ")
surname = input("enter surname: ")
gender = input ("enter gender: ")
age = input("enter age: ")
tribe = input ("enter tribe: ")
occupation = input("enter occupation: ")
(f"your information is  \n Name: {name} \n Surname: {surname} \n Gender: {gender} \n Age: {age} \n Tribe: {tribe} \n Occupation: {occupation} ")
# name = input("Enter your first name :")
# lastname = input("Enter your lastname: ")
# age = input("Enter your age: ")
# gender = input("Are you male or f emale:")
# state = input("Enter yout state of origin: ")
# occupation = input("What is your occupation: ")
# tribe = input("what is your tribe: ")
# print()
# print("customers Profile:\t")
# print("\tFull Name-" ,name, lastname)
# print("\tAge -",age)
# print("\tGender -",gender)
# print("\tState of origin -",state)
# print("\tOccupation -",occupation)
# print("\tTribe -",tribe)


